import { useRouter } from "next/router";
import Head from "next/head";

import { Navbar, Footer } from "../components/Atom";
import { Hero, Social } from "../components/Molecules";

import styles from "../styles/Landing.module.css";

const Layout = ({ children }) => {
  const route = useRouter();
  return (
    <div
      className={`text-[#2e3033] dark:text-[#ffffff] min-h-screen before:dark:bg-black/80 ${styles.bgMesh} relative z-10 before:content-[""] before:z-20 before:absolute before:w-full before:h-full before:bg-[#ffffff86] before:backdrop-blur-md`}
    >
      <Head>
        <title>R KHOIR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex flex-col justify-between relative z-30">
        <Navbar />
        {route.route !== "/" ? null : (
          <Hero>
            <Social />
          </Hero>
        )}
      </header>
      <main className="relative z-20 transition-all">{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
